export const downloadCopy = {
  "zh": {
    "androidIntro": "已实测 Samsung Galaxy Z Fold7 和 Fold8，其他机型未测试。请按下方各版本的测试范围选择。",
    "foldTitle1": "图片版",
    "foldTitle2": "专注你的画面",
    "foldIntro": "为内外双屏分别选图，让透视、磨砂与亮度跟随开合。",
    "foldDownload": "下载 Android Fold · 图片版",
    "foldCompatibility": "图片版已实测：Samsung Fold7（SM-F9660 / Android 16 / One UI 8.5）和 Fold8（SM-F9710 / Android 17 / One UI 9）。其他机型及固件未测试。",
    "foldBeta": "Beta · 需要 Shizuku。效果显示在 App 内，不替换系统桌面或其他 App。",
    "foldHelp": "图片版 · 安装与使用",
    "foldStep1": "下载 APK 并安装“折光 Fold”。现有用户可以直接覆盖升级，保留图片与参数。仅在系统提示时允许本次安装来源。",
    "foldStep2": "从官方渠道安装 Shizuku，通过无线调试或电脑启动。无需 Root；请使用调试模式启动。",
    "foldShizuku": "Shizuku 官方使用指南 ↗",
    "foldStep3": "打开折光 Fold，点“启用免 USB 感应”，允许此 App 的 Shizuku 授权，等待手机本地辅助连接。",
    "foldStep4": "选择内、外屏图片，点“全屏体验”。双指同时长按约 0.65 秒打开设置；配置完成后无需保持 USB 连接。",
    "foldReboot": "重启手机后需重新启动 Shizuku。若感应停止，先检查 Shizuku 是否运行及该 App 是否已授权。",
    "foldControls": "六项参数：外屏展开变暗 / 折叠变亮角度，内屏左侧展开变亮 / 折叠变暗角度，外屏右侧压缩和模糊程度。支持自动保存及恢复默认；内屏右半边保持清晰、静止。",
    "foldPower": "全屏时维持双屏运行，合拢后内屏也可能保持供电。双指长按返回设置或退出 App 可结束体验。请勿与全局版同时开启双屏效果。",
    "foldReadme": "完整使用说明",
    "foldChecksum": "SHA-256 校验值",
    "globalTitle1": "全局版",
    "globalTitle2": "随常用 App 开合",
    "globalIntro": "在各种兼容的 App 中，体验折叠效果",
    "globalDownload": "下载 Android Fold · 全局版",
    "globalCompatibility": "全局版目前仅在 Samsung Fold8（SM-F9710）实测；Fold7 的全局效果及其他机型未测试，当前构建不启用这些机型的双屏会话。",
    "globalBeta": "Beta · 已验证浏览器场景。动画期间画面短暂定格，不是实时视频。暂不支持桌面、最近任务、横屏及受保护页面。",
    "globalHelp": "全局版 · 安装与使用",
    "globalStep1": "先暂停图片版的全屏效果，再安装“折光·全局实验”。两款 App 的图片、参数与授权相互独立。",
    "globalStep2": "先启动 Shizuku，再打开全局版，点“1 授权连续角度”并允许它的独立授权。",
    "globalStep3": "点“2 授权屏幕效果”，在系统无障碍设置的已安装应用中启用“折光·全局实验”，然后返回 App 开启全局效果。",
    "globalStep4": "完全合拢一次，解锁外屏并打开浏览器，再缓慢展开。设置页提供六项参数、自动保存和恢复默认。",
    "globalStop": "停止方式：回到全局版设置页点“暂停全局效果”，或锁屏。画面中没有悬浮按钮。配置完成后可断开 USB；手机重启后需重新启动 Shizuku。",
    "globalPrivacy": "Shizuku 读取屏幕并迁移当前 App，无障碍服务显示效果层。截图只在本机内存中处理，不保存、不上传。双屏持续点亮会增加耗电。",
    "globalReadme": "完整使用说明",
    "globalChecksum": "SHA-256 校验值"
  },
  "en": {
    "androidIntro": "Tested on Samsung Galaxy Z Fold7 and Fold8. Other models are untested. Check the tested scope of each edition below.",
    "foldTitle1": "Photo edition",
    "foldTitle2": "A view of your own",
    "foldIntro": "Choose a picture for each screen. Perspective, frost and brightness follow the fold.",
    "foldDownload": "Download Android Fold · Photo",
    "foldCompatibility": "Photo edition tested on Samsung Fold7 (SM-F9660 / Android 16 / One UI 8.5) and Fold8 (SM-F9710 / Android 17 / One UI 9). Other models and firmware are untested.",
    "foldBeta": "Beta · Requires Shizuku. Effects stay inside this app; they do not replace the home screen or other apps.",
    "foldHelp": "Photo edition · Install and use",
    "foldStep1": "Download the APK and install Foldlight Fold. Existing users can update in place, keeping pictures and settings. If prompted, allow installation from this source.",
    "foldStep2": "Install Shizuku from its official source and start it through wireless debugging or a computer. Root is not required; use debugging mode.",
    "foldShizuku": "Official Shizuku setup guide ↗",
    "foldStep3": "Open Foldlight Fold. Tap the USB-free sensing button below the blue fullscreen button, approve this app in Shizuku, and wait for the local helper to connect. App labels are currently in Chinese.",
    "foldStep4": "Choose separate cover and inner pictures, then tap the blue fullscreen button. Hold two fingers together for about 0.65 seconds to open settings. USB is not needed after setup.",
    "foldReboot": "Restart Shizuku after rebooting your phone. If motion stops, check that Shizuku is running and this app is authorized.",
    "foldControls": "Six controls: cover opening dark-start and closing light-start angles; inner-left opening light-start and closing dark-start angles; cover right-edge compression and blur. Settings save automatically and can be reset. The inner right half stays clear and stationary.",
    "foldPower": "Fullscreen keeps both panels powered, including the inner panel when closed. Hold two fingers to return to settings, or leave the app to end the session. Do not enable both editions at the same time.",
    "foldReadme": "Full instructions in English",
    "foldChecksum": "SHA-256 checksum",
    "globalTitle1": "Global edition",
    "globalTitle2": "Follow your everyday apps",
    "globalIntro": "Experience folding effects across compatible apps.",
    "globalDownload": "Download Android Fold · Global",
    "globalCompatibility": "Global edition tested only on Samsung Fold8 (SM-F9710). Global effects on Fold7 and other models are untested; this build does not enable dual-screen sessions on those models.",
    "globalBeta": "Beta · Browser use has been verified. Content briefly freezes during transitions; this is not live video. Home, Recents, landscape and protected pages are not supported.",
    "globalHelp": "Global edition · Install and use",
    "globalStep1": "Stop the photo edition first, then install Foldlight Global Experiment. The two apps keep separate pictures, settings and permissions.",
    "globalStep2": "Start Shizuku, open the global edition, then tap permission button 1 and approve this app separately. App labels are currently in Chinese.",
    "globalStep3": "Tap permission button 2. Enable Foldlight Global Experiment under installed apps in Android Accessibility settings, then return and tap the blue enable button.",
    "globalStep4": "Close the phone fully once, unlock the cover and open a browser, then unfold slowly. The settings page has six controls, automatic saving and Restore defaults.",
    "globalStop": "To stop, return to the global app settings and tap the blue pause button, or lock the phone. There are no floating buttons. USB is not needed after setup; restart Shizuku after rebooting.",
    "globalPrivacy": "Shizuku captures the screen and moves the current app between displays; Accessibility hosts the effect layers. Screenshots stay in device memory and are neither saved nor uploaded. Keeping both panels powered uses more battery.",
    "globalReadme": "Full instructions in English",
    "globalChecksum": "SHA-256 checksum"
  }
};
